### ISSUE TITLE
Log-scale with population %

### ISSUE THREAD

**Issue by agamemnonc** [louisdecharson/covid-19#1]
Excellent dashboard, thank you.

It appears that when population % is enabled, the log-scale function doesn't do anything. Is this intentional?

**Comment by louisdecharson** [comment]
Hi,

Thanks. 
No it's not, I have not looked much into it yet but I believe that's because I am using d3 `scaleSymlog` for log-scaling. It's using the log transformation proposed by [Webber, 2013](https://www.researchgate.net/profile/John_Webber4/publication/233967063_A_bi-symmetric_log_transformation_for_wide-range_data/links/0fcfd50d791c85082e000000.pdf): `f(x) = ln(1 + x)` which can approximated by `f(x) = x` when x is close to 0.

I am looking into that !

**Comment by louisdecharson** [comment]
Fixed #267f00

**Comment by louisdecharson** [comment]
Fixed [#4591c5](https://github.com/louisdecharson/covid-19/commit/4591c56214516f108cc104da7a9cad056f73bd7e)
